class Message:
    def __init__(self, message, db_id=None, created_at=None, updated_at=None, version=0):
        """
        Args:
            message (str): message.
            db_id (int): id generated by the database when the entity was created.
            created_at (float): when the entity was created.
            updated_at (float): when the entity was updated. Currently an unused field by this app because there's no
                update logic in src/storage/daos/dao.py.
            version (int): version of the entity. Currently an unused field, but good practice to have a version field
                for backwards compatibility.
        """
        self.db_id = db_id
        self.message = message
        self.created_at = created_at
        self.updated_at = updated_at
        self.version = version